todofolder/todoproject/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
app_name='todoapp'

urlpatterns = [

    path('',views.add,name='add'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.TaskListview.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.TaskDetailView.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.TaskUpdateView.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.TaskDeleteView.as_view(),name='cbvdelete')
]

todofolder/todoproject/todoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]

todofolder/todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()

todofolder/todoproject/todoapp/forms.py
from django import forms
from .models import Task


class todoform(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todofolder/todoproject/todoapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from.models import Task
from.forms import todoform
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import UpdateView
from django.views.generic import DeleteView





class TaskListview(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task1'


class TaskDetailView(DetailView):
    model = Task
    template_name = 'details.html'
    context_object_name = 'task'

class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name','priority','date')
    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetail',kwargs={'pk':self.object.id})

class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')





# Create your views here.
def add(request):
    task1 = Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date=request.POST.get('date','')
        task=Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,"home.html",{"task1":task1})
# def details(request):
#
#     return render(request,"details.html")
def delete(request,taskid):
    if request.method=='POST':
        task=Task.objects.get(id=taskid)
        task.delete()
        return redirect('/')
    return render(request,"delete.html")

def update(request,id):
    task=Task.objects.get(id=id)
    form=todoform(request.POST or None,request.FILES,instance=task)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html")

todofolder/todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

todofolder/todoproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
<h4>Are you want to delete this task</h4><br>
<input type="submit" name="" value="confirm" class="btn btn-danger">
    </form>
</body>
</html>
{% endblock %}

todofolder/todoproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
  <div class="col-md-6">
            <h4>Task to be completed</h4>

       <div class="shadow card">
  <div class="card-header">
    <h4>{{task.name}}</h4>
  </div>
 <div class="card-body">

    <p class="card-text">{{task.priority}}</p>
       <p class="card-text">{{task.date}}</p>
    <a href="{% url 'todoapp:delete' task.id %}" class="btn btn-primary">Done</a>
      <a href="{% url 'todoapp:update' task.id %}"class="btn btn-success">Update</a>
  </div>

{% endblock %}

todofolder/todoproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}


<form  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <p><input type="text" name="name" placeholder="Enter your task"><br></p>
    <p><input type="text" name="priority" placeholder="Enter your priority"><br></p>
    <p><input type="date" name="date"><br></p>
    <p><input type="submit"  class="btn btn-primary" name="" value="confirm"></p>
</form>


{% endblock %}
   

todofolder/todoproject/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h4></h4>
        <form method="post" class="mb-3 shadow">
    {% csrf_token %}
            <div class="form-group">
    <input type="text" class="form-control" name="task" placeholder="Enter your task">
        </div>
    <div class="form-group">
    <input type="text" class="form-control" name="priority" placeholder="Enter your priority">
        <div class="form-group">
            <input type="date" name="date" >
        </div>
        </div>
    <input class="btn btn-success" type="submit">
            </form>




    </div>
        <div class="col-md-6">
            <h4>Task to be completed</h4>
            {% for i in task1 %}<br>
       <div class="shadow card">
  <div class="card-header">
    <h4>{{i.name}}</h4>
  </div>
  <div class="card-body">

    <p class="card-text">{{i.priority}}</p>
       <p class="card-text">{{i.date}}</p>
    <a href="{% url 'todoapp:delete' i.id %}" class="btn btn-primary">Done</a>
      <a href="{% url 'todoapp:update' i.id %}" class="btn btn-success">Update</a>
  </div>
</div>
            {% endfor %}
</div>
    </div>
</div>



















{% endblock %}

todofolder/todoproject/templates/update.html
{% extends 'base.html' %}
{% block body %}


<form  method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <p><input type="text" name="name" placeholder="Enter your task"><br></p>
    <p><input type="text" name="priority" placeholder="Enter your priority"><br></p>
    <p><input type="date" name="date"><br></p>
    <p><input type="submit"  class="btn btn-primary" name="" value="confirm"></p>
</form>


{% endblock %}